name: go-data-dict-codegen

run-name: ${{ github.actor }} generating go structs demo files

on:
  workflow_dispatch:

jobs:
  generate-go-structs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out action-go-proto-codegen
        uses: actions/checkout@v4

      - name: Check out my demo proto file
        uses: actions/checkout@v4
        with:
          repository: yumochi/twirp-demo
          path: protos
          ref: main

      # ... (previous steps remain the same) ...

      - name: Build Go module
        run: |
          mkdir generated
          cd generated
          go get google.golang.org/protobuf/reflect/protoreflect
          go get google.golang.org/protobuf/runtime/protoimpl
          go build ./...

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit generated code
        run: |
          cd generated
          git init
          git add .
          git commit -m "Add generated Go code"

      - name: Push generated code to your repository
        run: |
          cd generated
          git remote add origin https://github.com/your-username/your-repository.git
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload generated code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-go-code
          path: generated