name: go-data-dict-codegen
run-name: ${{ github.actor }} generating go structs demo files
on: 
  workflow_dispatch:
jobs:
  generate-go-structs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out action-go-proto-codegen
        uses: actions/checkout@v4
      - name: Check out my demo proto file
        uses: actions/checkout@v4
        with:
          repository: yumochi/twirp-demo
          path: protos
          ref: main

      - name: Verify code presence
        run: |
          echo "Listing contents of protos directory:"
          ls -la protos
          echo "Verifying specific files or directories:"
          if [ -d "protos/v1/proto" ]; then
            echo "Specific directory exists."
          else
            echo "Specific directory does not exist."
          fi
          if [ -f "protos/v1/proto/haberdasher.proto" ]; then
            echo "Specific file exists."
          else
            echo "Specific file does not exist."
          fi
