name: go-data-dict-codegen

run-name: ${{ github.actor }} generating go structs demo files

on:
  workflow_dispatch:

jobs:
  generate-go-structs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out action-go-proto-codegen
        uses: actions/checkout@v4

      - name: Check out my demo proto file
        uses: actions/checkout@v4
        with:
          repository: yumochi/twirp-demo
          path: protos
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
  
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
  
      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
  
      - name: Generate Go code
        run: |
          mkdir -p generated
          protoc --go_out=./generated --go_opt=paths=source_relative protos/v1/proto/haberdasher.proto
  
      - name: Initialize Go module
        run: |
          cd generated
          go mod init github.com/your-username/twirp-demo-go

      - name: Build Go module
        run: |
          cd generated
          go get google.golang.org/protobuf/reflect/protoreflect
          go get google.golang.org/protobuf/runtime/protoimpl
          go build ./...

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit generated code
        run: |
          cd generated
          git init
          git add .
          git commit -m "Add generated Go code"

      - name: Push generated code to your repository
        run: |
          cd generated
          git remote add origin https://github.com/your-username/your-repository.git
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload generated code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-go-code
          path: generated